### ISSUE TITLE
"Duplicate filename" after second compression of same data

### ISSUE THREAD

**Issue by Nemulation** [MartyShepard/Drop7z#1]
Dear MartyShepard,

thank you for this great tool! Really helpful!

I´ve found one issue and have two suggestions:
**Issue:** If I add several files to the list and compress them, then empty the list and add the same files again (with the same settings), the compression process stops with the message "Duplicate Filename". Screenshot:
![duplicate filename](https://user-images.githubusercontent.com/126714921/222249657-b1976c63-a774-47f2-9350-717d954920f5.jpg)

**Suggestion 1:** It would be nice to have one button to empty the List.

**Suggestion 2:** NoHide -It would be handy if you could set a temporary check mark somewhere for the drag&drop procedure, so that Drop7zip stays in the foreground and is not hidden behind other windows when you select the files (e.g. from Explorer). This could be useful for notebook-users.

System: Win7 64

Thank you for your support
Nemulation

**Comment by MartyShepard** [comment]
Thanks for you comment :)

To 1. The bug should be gone. I completely forgot about that. 

You can clear by the right mouse "popup menu" in the filelister. -> remove all  items but I think you mean as a "quick button" on the Gui?.

to 2. Check the the right mouse "popup menu"  -> Settings -> Always on Top

greetings

**Comment by Nemulation** [comment]
Yeah! Works fine now! Many thanks for the fix!

For Clearing the List: Yes, i mean a quick-Button. 

Thank you for always on top. Also works fine!

Since update there some changes in GUI, right? Some of the fonts/font sizes no longer fit:
![drop7zip](https://user-images.githubusercontent.com/126714921/222815061-05369700-1c56-4959-bf99-0a818713abaf.jpg)

Best!

**Comment by MartyShepard** [comment]
Yes .. damnded .. its now fixed. MemFont Resource Fixed

**Comment by MartyShepard** [comment]
Looks good ... i close this topic
